name: Ansi
version: '${version}'

main: de.lifemytouch.ansi.Ansi
api-version: '1.21'

commands:
  timer:
    description: Verwaltet den Timer
  gm:
    description: Verwaltet den Gamemode eines Spielers
  rang:
    description: Verwaltet den Rang eines Spielers
  challenge:
    description: Verwaltet Challenges
  report:
    description: Meldet einen Spieler
  reports:
    description: Öffnet die Report-Liste
  fly:
    description: Erlaubt dem Spieler das Fliegen
  vanish:
    description: Versteckt den Spieler vor anderen
  ban:
    description: Bannt einen Spieler
  mute:
    description: Muted einen Spieler
  kick:
    description: Kickt einen Spieler
  history:
    description: Zeigt die Punish History eines Spielers
  unpunish:
    description: Hebt die Sperre eines Spielers auf
  lobby:
    description: Teleportiert dich zum Spawn der Lobby